//! # Python-TensorFlow Bridge
//!
//! Utilities for importing Python-trained TensorFlow/Keras models into Rust,
//! including ONNX import helpers and weight migration tools.

use std::path::Path;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use tracing::{debug, info};

/// Metadata for a Python-trained model being imported.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelMetadata {
    /// Model name/identifier.
    pub name: String,
    /// Framework used for training ("tensorflow", "keras", "pytorch").
    pub framework: String,
    /// Model version or git hash.
    pub version: String,
    /// Input layer names and shapes.
    pub inputs: Vec<LayerInfo>,
    /// Output layer names and shapes.
    pub outputs: Vec<LayerInfo>,
    /// Training date (ISO 8601).
    pub trained_at: String,
    /// Key training hyperparameters.
    pub hyperparams: std::collections::HashMap<String, serde_json::Value>,
}

/// Information about a model layer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LayerInfo {
    pub name: String,
    pub dtype: String,
    pub shape: Vec<usize>,
}

/// Bridge for loading Python-trained TensorFlow models into Rust.
pub struct PyTfBridge {
    metadata: ModelMetadata,
    model_path: std::path::PathBuf,
}

impl PyTfBridge {
    /// Create a new bridge by pointing to a Python-trained model directory.
    ///
    /// The directory should contain a `model_metadata.json` file and the
    /// SavedModel or frozen graph files.
    pub fn new(model_path: &Path) -> Result<Self> {
        let meta_path = model_path.join("model_metadata.json");
        if !meta_path.exists() {
            // Generate default metadata
            let metadata = ModelMetadata {
                name: model_path
                    .file_name()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .to_string(),
                framework: "tensorflow".to_string(),
                version: "0.1.0".to_string(),
                inputs: vec![],
                outputs: vec![],
                trained_at: chrono::Utc::now().to_rfc3339(),
                hyperparams: std::collections::HashMap::new(),
            };
            info!(
                path = %model_path.display(),
                "No model_metadata.json found, generating defaults"
            );
            return Ok(Self {
                metadata,
                model_path: model_path.to_path_buf(),
            });
        }

        let content = std::fs::read_to_string(&meta_path)
            .with_context(|| format!("Reading {}", meta_path.display()))?;
        let metadata: ModelMetadata =
            serde_json::from_str(&content).context("Parsing model_metadata.json")?;
        info!(
            name = %metadata.name,
            framework = %metadata.framework,
            "Loaded model metadata"
        );
        Ok(Self {
            metadata,
            model_path: model_path.to_path_buf(),
        })
    }

    /// Get the model metadata.
    pub fn metadata(&self) -> &ModelMetadata {
        &self.metadata
    }

    /// Get the model path.
    pub fn path(&self) -> &Path {
        &self.model_path
    }

    /// Generate a Rust inference wrapper based on the model metadata.
    ///
    /// Produces Rust source code that wraps the loaded model with
    /// type-safe input/output structs matching the model's signature.
    pub fn generate_wrapper(&self) -> Result<String> {
        let name = &self.metadata.name;
        let safe_name: String = name.chars().filter(|c| c.is_alphanumeric() || *c == '_').collect();
        let mut code = String::new();

        code.push_str(&format!(
            r#"//! Auto-generated wrapper for model: {name}
//!
//! Generated by cubiczan-ml-tf bridge.
//! Do not edit manually.

use cubiczan_ml_tf::session::{{TfSession, SessionConfig}};
use anyhow::Result;
use ndarray::ArrayD;

pub struct {safe_name}Model {{
    session: TfSession,
}}

impl {safe_name}Model {{
    /// Load the model from the given path.
    pub fn load(model_path: &std::path::Path) -> Result<Self> {{
        let inputs = vec![];
        let outputs = vec![];
        let session = TfSession::from_saved_model(
            "{safe_name}",
            model_path,
            inputs,
            outputs,
            SessionConfig::default(),
        )?;
        Ok(Self {{ session }})
    }}

    /// Run inference.
    pub fn predict(&mut self, input: &ArrayD<f32>) -> Result<ArrayD<f32>> {{
        let results = self.session.run(&[("input", input.clone())])?;
        results.into_iter().next()
            .map(|(_, t)| t)
            .context("No output from model")
    }}
}}
"#
        ));

        Ok(code)
    }

    /// Validate that the model files are compatible with the metadata.
    pub fn validate(&self) -> Result<ValidationReport> {
        let mut issues = Vec::new();
        let mut warnings = Vec::new();

        // Check for SavedModel directory structure
        let saved_model_pb = self.model_path.join("saved_model.pb");
        let variables_dir = self.model_path.join("variables");

        if saved_model_pb.exists() {
            debug!("Found saved_model.pb");
        } else {
            issues.push("saved_model.pb not found".to_string());
        }

        if variables_dir.exists() {
            debug!("Found variables/ directory");
        } else if !saved_model_pb.exists() {
            issues.push("variables/ directory not found".to_string());
        }

        // Check for frozen graph alternative
        let frozen_graph = self.model_path.join("frozen_graph.pb");
        if frozen_graph.exists() {
            debug!("Found frozen_graph.pb as alternative");
        }

        if self.metadata.inputs.is_empty() {
            warnings.push("No input layers defined in metadata".to_string());
        }
        if self.metadata.outputs.is_empty() {
            warnings.push("No output layers defined in metadata".to_string());
        }

        Ok(ValidationReport { issues, warnings })
    }
}

/// Report from model validation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidationReport {
    pub issues: Vec<String>,
    pub warnings: Vec<String>,
}

impl ValidationReport {
    /// Whether the model passed validation.
    pub fn is_valid(&self) -> bool {
        self.issues.is_empty()
    }
}

/// Helper for importing ONNX models.
pub struct OnnxImporter;

impl OnnxImporter {
    /// Check if an ONNX model file is valid by reading its header.
    ///
    /// ONNX files start with an 8-byte magic number followed by protobuf.
    pub fn validate_onnx_file(path: &Path) -> Result<bool> {
        let mut buf = [0u8; 8];
        let mut file = std::fs::File::open(path)
            .with_context(|| format!("Opening {}", path.display()))?;
        std::io::Read::read_exact(&mut file, &mut buf)
            .with_context(|| format!("Reading header of {}", path.display()))?;

        // ONNX magic: 0x08 followed by protobuf field
        // Simple heuristic: first byte should be small (field number)
        let valid = buf[0] <= 0x0F;
        if valid {
            debug!(path = %path.display(), "ONNX file appears valid");
        }
        Ok(valid)
    }

    /// Get the file size of an ONNX model.
    pub fn model_size(path: &Path) -> Result<u64> {
        let metadata = std::fs::metadata(path)
            .with_context(|| format!("Getting metadata for {}", path.display()))?;
        Ok(metadata.len())
    }

    /// Convert ONNX model path to a TF-compatible SavedModel path suggestion.
    ///
    /// This returns a suggested output path, it does not perform conversion.
    pub fn suggest_conversion_path(onnx_path: &Path) -> std::path::PathBuf {
        let stem = onnx_path
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        onnx_path
            .parent()
            .unwrap_or(Path::new("."))
            .join(format!("{}_saved_model", stem))
    }
}

/// Weight migration utilities for moving model weights between frameworks.
pub struct WeightMigrator;

impl WeightMigrator {
    /// Load weights from a numpy .npy file into an ndarray.
    ///
    /// Supports .npy format (version 1.0, 2.0, 3.0).
    pub fn load_npy(path: &Path) -> Result<ndarray::ArrayD<f32>> {
        let content = std::fs::read(path)
            .with_context(|| format!("Reading npy file {}", path.display()))?;

        // Check magic: \x93NUMPY
        if content.len() < 8 || &content[0..6] != b"\x93NUMPY" {
            anyhow::bail!("Not a valid .npy file: {}", path.display());
        }

        let major = content[6] as u32;
        let minor = content[7] as u32;
        let header_len_start = 8 + match major {
            1 => 2,  // uint16
            2 => 4,  // uint32
            3 => 4,  // uint32
            _ => anyhow::bail!("Unsupported npy version: {}.{}", major, minor),
        };

        let header_len = match major {
            1 => u16::from_le_bytes([content[8], content[9]]) as usize,
            2 | 3 => u32::from_le_bytes([content[8], content[9], content[10], content[11]]) as usize,
            _ => unreachable!(),
        };

        let data_start = header_len_start + header_len;
        if data_start >= content.len() {
            anyhow::bail!("Invalid npy file: header extends beyond file");
        }

        let data = &content[data_start..];
        let float_count = data.len() / 4;
        let mut weights = Vec::with_capacity(float_count);
        for i in 0..float_count {
            let bytes: [u8; 4] = [data[i * 4], data[i * 4 + 1], data[i * 4 + 2], data[i * 4 + 3]];
            weights.push(f32::from_le_bytes(bytes));
        }

        // For a simple 2D weight matrix, reshape to (rows, cols)
        // For now, return as 1D and let the caller reshape.
        Ok(ndarray::ArrayD::from_shape_vec(
            ndarray::IxDyn(&[weights.len()]),
            weights,
        )?)
    }

    /// Save weights from an ndarray to a binary file.
    pub fn save_weights(path: &Path, weights: &ndarray::ArrayD<f32>) -> Result<()> {
        let bytes: Vec<u8> = weights
            .iter()
            .flat_map(|f| f.to_le_bytes())
            .collect();
        std::fs::write(path, &bytes)
            .with_context(|| format!("Writing weights to {}", path.display()))?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bridge_with_nonexistent_path() {
        let bridge = PyTfBridge::new(Path::new("/nonexistent")).unwrap();
        assert_eq!(bridge.metadata().framework, "tensorflow");
        // A nonexistent path should fail validation (no saved_model.pb)
        assert!(!bridge.validate().unwrap().is_valid());
    }

    #[test]
    fn test_wrapper_generation() {
        let bridge = PyTfBridge::new(Path::new("/tmp/test_model")).unwrap();
        let code = bridge.generate_wrapper().unwrap();
        assert!(code.contains("fn predict"));
    }

    #[test]
    fn test_onnx_validate_nonexistent() {
        let result = OnnxImporter::validate_onnx_file(Path::new("/nonexistent.onnx"));
        assert!(result.is_err());
    }

    #[test]
    fn test_onnx_suggest_path() {
        let suggested = OnnxImporter::suggest_conversion_path(Path::new("/models/model.onnx"));
        assert!(suggested.to_string_lossy().contains("model_saved_model"));
    }
}
