/// MeanFlow Policy — Flow-matching generative policy for HFT.
///
/// Implements a conditional flow-matching model where the policy action
/// is generated by transporting noise through a learned velocity field
/// conditioned on market state.
///
/// The flow matching objective is:
///     L = E_{t, x_0, x_1} || v_theta(x_t, t, cond) - (x_1 - x_0)||^2
///
/// where x_0 ~ N(0,I), x_1 is the expert action, and x_t = (1-t)*x_0 + t*x_1.

use ndarray::{Array1, Array2, concatenate, Axis};
use rand::prelude::*;
use rand_distr::StandardNormal;
use std::collections::HashMap;

/// Conditional flow-matching policy for continuous actions in HFT.
///
/// Architecture:
///     obs -> [FiLM-conditioned MLP] -> velocity field v(x_t, t)
///     x_0 ~ N(0, I), x_1 = expert_action
///     x_t = (1-t)*x_0 + t*x_1
///     sampled_action = integrate velocity field from t=0 to t=1
#[derive(Debug, Clone)]
pub struct MeanFlowPolicy {
    pub obs_dim: usize,
    pub act_dim: usize,
    pub hidden_sizes: Vec<usize>,
    pub n_flow_steps: usize,

    /// Velocity network weights (list of 2D arrays).
    pub vel_weights: Vec<Array2<f64>>,
    /// Velocity network biases (list of 1D arrays).
    pub vel_biases: Vec<Array1<f64>>,

    /// FiLM gamma (scale) parameter for the last hidden layer.
    pub film_gamma: Array1<f64>,
    /// FiLM beta (shift) parameter for the last hidden layer.
    pub film_beta: Array1<f64>,
    /// FiLM projection weight from obs to gamma.
    pub W_film: Array2<f64>,
    /// FiLM projection bias.
    pub b_film: Array1<f64>,
}

impl MeanFlowPolicy {
    /// Create a new MeanFlow policy with He initialization.
    pub fn new(obs_dim: usize, act_dim: usize, hidden_sizes: Vec<usize>, n_flow_steps: usize) -> Self {
        let mut rng = rand::thread_rng();
        let vel_input_dim = act_dim + 1 + obs_dim;

        let mut vel_weights = Vec::new();
        let mut vel_biases = Vec::new();
        let mut prev_dim = vel_input_dim;

        for &h in &hidden_sizes {
            let scale = (2.0 / prev_dim as f64).sqrt();
            let w = Array2::from_shape_fn((prev_dim, h), |_| {
                rng.sample::<f64, _>(StandardNormal) * scale
            });
            let b = Array1::zeros(h);
            vel_weights.push(w);
            vel_biases.push(b);
            prev_dim = h;
        }

        // Output layer
        let scale = (2.0 / prev_dim as f64).sqrt();
        let w_out = Array2::from_shape_fn((prev_dim, act_dim), |_| {
            rng.sample::<f64, _>(StandardNormal) * scale
        });
        let b_out = Array1::zeros(act_dim);
        vel_weights.push(w_out);
        vel_biases.push(b_out);

        // FiLM conditioning on observation
        let last_hidden = hidden_sizes.last().copied().unwrap_or(64);
        let film_gamma = Array1::ones(last_hidden);
        let film_beta = Array1::zeros(last_hidden);

        let film_scale = (2.0 / obs_dim as f64).sqrt();
        let W_film = Array2::from_shape_fn((obs_dim, last_hidden), |_| {
            rng.sample::<f64, _>(StandardNormal) * film_scale
        });
        let b_film = Array1::zeros(last_hidden);

        Self {
            obs_dim,
            act_dim,
            hidden_sizes,
            n_flow_steps,
            vel_weights,
            vel_biases,
            film_gamma,
            film_beta,
            W_film,
            b_film,
        }
    }

    /// Create with sensible defaults for hidden_sizes and flow steps.
    pub fn new_default(obs_dim: usize, act_dim: usize) -> Self {
        Self::new(obs_dim, act_dim, vec![128, 128, 64], 10)
    }

    /// Total number of trainable parameters.
    pub fn n_params(&self) -> usize {
        let mut total = 0;
        for (w, b) in self.vel_weights.iter().zip(self.vel_biases.iter()) {
            total += w.len();
            total += b.len();
        }
        total += self.film_gamma.len();
        total += self.film_beta.len();
        total += self.W_film.len();
        total += self.b_film.len();
        total
    }

    /// Compute velocity field v(x_t, t, obs).
    pub fn velocity_network(&self, x_t: &Array1<f64>, t: f64, obs: &Array1<f64>) -> Array1<f64> {
        let t_arr = Array1::from_elem(1, t);
        let x_in = concatenate![Axis(0), x_t.view(), t_arr.view(), obs.view()];

        let n_layers = self.vel_weights.len();
        let mut hidden = x_in;

        for i in 0..n_layers {
            hidden = hidden.dot(&self.vel_weights[i]) + &self.vel_biases[i];
            if i < n_layers - 1 {
                hidden = hidden.mapv(|v| v.tanh());
                // Apply FiLM on the last hidden layer
                if i == n_layers - 2 {
                    let gamma = obs.dot(&self.W_film) + &self.b_film;
                    let gamma = &gamma * &self.film_gamma + &self.film_beta;
                    hidden = &gamma * &hidden;
                }
            }
        }
        hidden
    }

    /// Compute flow-matching loss: ||v_theta - (x_1 - x_0)||^2.
    pub fn flow_loss(
        &self,
        obs: &Array1<f64>,
        expert_action: &Array1<f64>,
        rng: &mut StdRng,
    ) -> f64 {
        let t: f64 = rng.gen();
        let x_0: Array1<f64> = Array1::from_shape_fn(self.act_dim, |_| rng.sample(StandardNormal));
        let x_t = (1.0 - t) * &x_0 + t * expert_action;
        let target_velocity = expert_action - &x_0;
        let pred_velocity = self.velocity_network(&x_t, t, obs);
        let diff = &pred_velocity - &target_velocity;
        diff.mapv(|v| v * v).mean().unwrap_or(0.0)
    }

    /// Sample action via Euler integration of the flow ODE.
    ///
    /// dx/dt = v_theta(x_t, t, obs), from t=0 (noise) to t=1 (action)
    pub fn act(&self, obs: &Array1<f64>, rng: &mut StdRng, deterministic: bool) -> Array1<f64> {
        let x = if deterministic {
            Array1::zeros(self.act_dim)
        } else {
            Array1::from_shape_fn(self.act_dim, |_| rng.sample(StandardNormal))
        };
        let dt = 1.0 / self.n_flow_steps as f64;
        let mut current = x;
        for step in 0..self.n_flow_steps {
            let t = step as f64 * dt;
            let v = self.velocity_network(&current, t, obs);
            current = &current + &v * dt;
        }
        current
    }

    /// Get all trainable parameters as a HashMap.
    pub fn get_params(&self) -> HashMap<String, serde_json::Value> {
        let mut map = HashMap::new();

        // Serialize weights and biases as nested arrays
        let weights: Vec<Vec<Vec<f64>>> = self
            .vel_weights
            .iter()
            .map(|w| w.rows().into_iter().map(|r| r.to_vec()).collect())
            .collect();
        let biases: Vec<Vec<f64>> = self.vel_biases.iter().map(|b| b.to_vec()).collect();

        map.insert("vel_weights".to_string(), serde_json::json!(weights));
        map.insert("vel_biases".to_string(), serde_json::json!(biases));
        map.insert(
            "film_gamma".to_string(),
            serde_json::json!(self.film_gamma.to_vec()),
        );
        map.insert(
            "film_beta".to_string(),
            serde_json::json!(self.film_beta.to_vec()),
        );
        map.insert(
            "W_film".to_string(),
            serde_json::json!(
                self.W_film
                    .rows()
                    .into_iter()
                    .map(|r| r.to_vec())
                    .collect::<Vec<_>>()
            ),
        );
        map.insert(
            "b_film".to_string(),
            serde_json::json!(self.b_film.to_vec()),
        );

        map
    }

    /// Set all trainable parameters from a HashMap.
    pub fn set_params(&mut self, params: &HashMap<String, serde_json::Value>) {
        if let Some(v) = params.get("vel_weights") {
            if let Some(arr) = v.as_array() {
                let mut new_weights = Vec::new();
                for row_2d in arr {
                    if let Some(rows) = row_2d.as_array() {
                        let matrix: Vec<Vec<f64>> =
                            rows.iter().map(|r| json_to_f64_vec(r)).collect();
                        if let Ok(arr2) = Array2::from_shape_vec(
                            (matrix.len(), if matrix.is_empty() { 0 } else { matrix[0].len() }),
                            matrix.into_iter().flatten().collect(),
                        ) {
                            new_weights.push(arr2);
                        }
                    }
                }
                if new_weights.len() == self.vel_weights.len() {
                    self.vel_weights = new_weights;
                }
            }
        }

        if let Some(v) = params.get("vel_biases") {
            if let Some(arr) = v.as_array() {
                let mut new_biases = Vec::new();
                for item in arr {
                    let vec = json_to_f64_vec(item);
                    new_biases.push(Array1::from_vec(vec));
                }
                if new_biases.len() == self.vel_biases.len() {
                    self.vel_biases = new_biases;
                }
            }
        }

        if let Some(v) = params.get("film_gamma") {
            if let Ok(arr) = json_to_array1(v) {
                self.film_gamma = arr;
            }
        }
        if let Some(v) = params.get("film_beta") {
            if let Ok(arr) = json_to_array1(v) {
                self.film_beta = arr;
            }
        }
        if let Some(v) = params.get("W_film") {
            if let Some(arr) = v.as_array() {
                let matrix: Vec<Vec<f64>> =
                    arr.iter().map(|r| json_to_f64_vec(r)).collect();
                if !matrix.is_empty() {
                    if let Ok(arr2) = Array2::from_shape_vec(
                        (matrix.len(), matrix[0].len()),
                        matrix.into_iter().flatten().collect(),
                    ) {
                        self.W_film = arr2;
                    }
                }
            }
        }
        if let Some(v) = params.get("b_film") {
            if let Ok(arr) = json_to_array1(v) {
                self.b_film = arr;
            }
        }
    }
}

/// Helper: JSON Value to Vec<f64>.
fn json_to_f64_vec(v: &serde_json::Value) -> Vec<f64> {
    v.as_array()
        .map(|arr| {
            arr.iter()
                .map(|x| x.as_f64().unwrap_or(0.0))
                .collect()
        })
        .unwrap_or_default()
}

/// Helper: JSON Value to Array1<f64>.
fn json_to_array1(v: &serde_json::Value) -> Result<Array1<f64>, ()> {
    let vec = json_to_f64_vec(v);
    Ok(Array1::from_vec(vec))
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::SeedableRng;

    fn array_close(a: &Array1<f64>, b: &Array1<f64>, tol: f64) -> bool {
        if a.len() != b.len() {
            return false;
        }
        for i in 0..a.len() {
            if (a[i] - b[i]).abs() > tol {
                return false;
            }
        }
        true
    }

    #[test]
    fn test_meanflow_creation() {
        let policy = MeanFlowPolicy::new_default(6, 1);
        assert_eq!(policy.obs_dim, 6);
        assert_eq!(policy.act_dim, 1);
        assert!(policy.n_params() > 0);
    }

    #[test]
    fn test_meanflow_params() {
        let policy = MeanFlowPolicy::new_default(6, 1);
        let params = policy.get_params();
        assert!(params.contains_key("vel_weights"));

        let mut policy2 = MeanFlowPolicy::new_default(6, 1);
        policy2.set_params(&params);

        let mut rng = StdRng::seed_from_u64(42);
        let obs = Array1::from_vec(vec![0.1, 0.2, 0.3, 0.4, 0.5, 0.6]);
        let a1 = policy.act(&obs, &mut rng, true);
        let a2 = policy2.act(&obs, &mut rng, true);
        assert!(array_close(&a1, &a2, 1e-10));
    }

    #[test]
    fn test_meanflow_loss() {
        let policy = MeanFlowPolicy::new_default(6, 1);
        let obs = Array1::from_vec(vec![0.1, 0.2, 0.3, 0.4, 0.5, 0.6]);
        let action = Array1::from_vec(vec![0.5]);
        let mut rng = StdRng::seed_from_u64(42);
        let loss = policy.flow_loss(&obs, &action, &mut rng);
        assert!(loss >= 0.0);
        assert!(loss.is_finite());
    }

    #[test]
    fn test_meanflow_act() {
        let policy = MeanFlowPolicy::new_default(6, 1);
        let obs = Array1::from_vec(vec![0.1, 0.2, 0.3, 0.4, 0.5, 0.6]);
        let mut rng = StdRng::seed_from_u64(42);
        let action = policy.act(&obs, &mut rng, false);
        assert_eq!(action.len(), 1);
        for v in action.iter() {
            assert!(v.is_finite());
        }
    }
}
